In [1]:
import pandas as pd
from uuid import uuid4

### GATHERING ALL players

In [2]:
players = pd.read_csv('./dataset/IPL_TEAMS - PLAYER_2025.csv')

In [3]:
players.head(5)

           PLAYER_NAME PLAYER_TYPE IPL_TEAM
0       Mitchell Starc      Bowler       DC
1         T. Natarajan      Bowler       DC
2         Mohit Sharma      Bowler       DC
3         Mukesh Kumar      Bowler       DC
4  Dushmantha Chameera      Bowler       DC

In [4]:
players['PLAYER_TYPE'].unique()

array(['Bowler', 'WK-Batter', 'Batter', 'All-Rounder'], dtype=object)

In [5]:
players.columns

Index(['PLAYER_NAME', 'PLAYER_TYPE', 'IPL_TEAM'], dtype='object')

In [6]:
players_id = []
for i in range(players['PLAYER_NAME'].count()):
    players_id.append(str(uuid4()))

In [7]:
players['PLAYER_ID'] = players_id

In [8]:
match_cols = [
    'IPL', 'T20I', 'ODI', 'STATE_T20', 'SMAT_ELITE',
    'VIJAY_HAZARE', 'VINOO_MANKAD', 'DULEEP_TROPHY',
    'RANJI_TROPHY', 'BBL', 'CPL', 'SA20', 'ILT20'
]
MASTER_DATA = []

for player in players.iterrows():
    
    temp = []
    for i in match_cols:
        data = {
            'PLAYER_ID': player[1][3]+'_'+i,
            'PLAYER_NAME': player[1][0],
            'PLAYER_TYPE': player[1][1],
            'PLAYER_IPL_TEAM': player[1][2],
        }
        temp.append(data)

    MASTER_DATA.extend(temp)

/var/folders/xx/z_z148gs3vg49g9p4_26bbph0000gn/T/ipykernel_6218/1020615054.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'PLAYER_ID': player[1][3]+'_'+i,
/var/folders/xx/z_z148gs3vg49g9p4_26bbph0000gn/T/ipykernel_6218/1020615054.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'PLAYER_NAME': player[1][0],
/var/folders/xx/z_z148gs3vg49g9p4_26bbph0000gn/T/ipykernel_6218/1020615054.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'PLAYER_TYPE': player[1][1],
/var/folders/xx/z_z148gs3vg49g9p4_26bbph0000gn/T/ipykernel_6218/1020615054.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'PLAYER_IPL_TEAM': player[1][2],

In [9]:
players = pd.DataFrame(MASTER_DATA)

In [10]:
players

,PLAYER_ID,PLAYER_NAME,PLAYER_TYPE,PLAYER_IPL_TEAM
0,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_IPL,Mitchell Starc,Bowler,DC
1,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_T20I,Mitchell Starc,Bowler,DC
2,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_ODI,Mitchell Starc,Bowler,DC
3,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_STATE_T20,Mitchell Starc,Bowler,DC
4,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_SMAT_ELITE,Mitchell Starc,Bowler,DC
...,...,...,...,...
3050,44c1267e-0a0e-4b37-a6aa-ebf5eaabd15b_RANJI_TROPHY,Manoj Bhandage,All-Rounder,RCB
3051,44c1267e-0a0e-4b37-a6aa-ebf5eaabd15b_BBL,Manoj Bhandage,All-Rounder,RCB
3052,44c1267e-0a0e-4b37-a6aa-ebf5eaabd15b_CPL,Manoj Bhandage,All-Rounder,RCB
3053,44c1267e-0a0e-4b37-a6aa-ebf5eaabd15b_SA20,Manoj Bhandage,All-Rounder,RCB
3054,44c1267e-0a0e-4b37-a6aa-ebf5eaabd15b_ILT20,Manoj Bhandage,All-Rounder,RCB

In [11]:
players.set_index('PLAYER_ID', inplace=True)

### 1. Splitting Players into Batsman and Blowers

1.(a) extracting batsman from the players

In [12]:
batsman = players[
    (players['PLAYER_TYPE'] == 'Batter') |
    (players['PLAYER_TYPE'] == 'WK-Batter') |
    (players['PLAYER_TYPE'] == 'All-Rounder')
].copy()

In [13]:
batsman.head(5)

,PLAYER_NAME,PLAYER_TYPE,PLAYER_IPL_TEAM
PLAYER_ID,,,
c6182645-54c7-4535-9012-895e2dd841eb_IPL,KL Rahul,WK-Batter,DC
c6182645-54c7-4535-9012-895e2dd841eb_T20I,KL Rahul,WK-Batter,DC
c6182645-54c7-4535-9012-895e2dd841eb_ODI,KL Rahul,WK-Batter,DC
c6182645-54c7-4535-9012-895e2dd841eb_STATE_T20,KL Rahul,WK-Batter,DC
c6182645-54c7-4535-9012-895e2dd841eb_SMAT_ELITE,KL Rahul,WK-Batter,DC

In [14]:
batsman['PLAYER_TYPE'].unique()

array(['WK-Batter', 'Batter', 'All-Rounder'], dtype=object)

In [15]:
batsman.count()

PLAYER_NAME        1911
PLAYER_TYPE        1911
PLAYER_IPL_TEAM    1911
dtype: int64

In [16]:
batsman['TOTAL_RUNS'] = 0.0
batsman['BATTING_AVG'] = 0.0
batsman['30+RUNS'] = 0.0
batsman['50+RUNS'] = 0.0
batsman['70+RUNS'] = 0.0
batsman['S/R_vs_SPIN'] = 0.0
batsman['S/R_vs_PACE'] = 0.0
batsman['HIGHEST_SCORED'] = 0.0
batsman['NOT_OUTS'] = 0.0
batsman['BOUNDARY_%'] = 0.0
batsman['DOT_BALLS_%'] = 0.0
batsman['BALLS_FACED'] = 0.0
batsman['CATCHES_TAKEN'] = 0.0
batsman['CATCHES_DROPPED'] = 0.0
batsman['RUN_OUT_(%)'] = 0.0
batsman['RUNS_SAVED'] = 0.0
batsman['BOUNDARIES_SAVED'] = 0.0
batsman['CAUGHT_BEHIND'] = 0.0
batsman['STUMPING'] = 0.0
batsman['RUNS_SAVED'] = 0.0
batsman['RUN_OUTS'] = 0.0

In [17]:
batsman.columns

Index(['PLAYER_NAME', 'PLAYER_TYPE', 'PLAYER_IPL_TEAM', 'TOTAL_RUNS',
       'BATTING_AVG', '30+RUNS', '50+RUNS', '70+RUNS', 'S/R_vs_SPIN',
       'S/R_vs_PACE', 'HIGHEST_SCORED', 'NOT_OUTS', 'BOUNDARY_%',
       'DOT_BALLS_%', 'BALLS_FACED', 'CATCHES_TAKEN', 'CATCHES_DROPPED',
       'RUN_OUT_(%)', 'RUNS_SAVED', 'BOUNDARIES_SAVED', 'CAUGHT_BEHIND',
       'STUMPING', 'RUN_OUTS'],
      dtype='object')

In [18]:
batsman.head(5)

,PLAYER_NAME,PLAYER_TYPE,PLAYER_IPL_TEAM,TOTAL_RUNS,BATTING_AVG,30+RUNS,50+RUNS,70+RUNS,S/R_vs_SPIN,S/R_vs_PACE,...,DOT_BALLS_%,BALLS_FACED,CATCHES_TAKEN,CATCHES_DROPPED,RUN_OUT_(%),RUNS_SAVED,BOUNDARIES_SAVED,CAUGHT_BEHIND,STUMPING,RUN_OUTS
PLAYER_ID,,,,,,,,,,,,,,,,,,,,,
c6182645-54c7-4535-9012-895e2dd841eb_IPL,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c6182645-54c7-4535-9012-895e2dd841eb_T20I,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c6182645-54c7-4535-9012-895e2dd841eb_ODI,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c6182645-54c7-4535-9012-895e2dd841eb_STATE_T20,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c6182645-54c7-4535-9012-895e2dd841eb_SMAT_ELITE,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

1.(b) extracting batsman from the players

In [19]:
bowlers = players[
    (players['PLAYER_TYPE'] == 'Bowler') |
    (players['PLAYER_TYPE'] == 'All-Rounder')
].copy()

In [20]:
bowlers['PLAYER_TYPE'].unique()

array(['Bowler', 'All-Rounder'], dtype=object)

In [21]:
bowlers.count()

PLAYER_NAME        2067
PLAYER_TYPE        2067
PLAYER_IPL_TEAM    2067
dtype: int64

In [22]:
bowlers['TOTAL_WICKETS'] = 0.0
bowlers['BOWLING_AVG'] = 0.0
bowlers['ECONOMY_RATE'] = 0.0
bowlers['2WK_HAULS'] = 0.0
bowlers['3WK_HAULS'] = 0.0
bowlers['4WK_HAULS'] = 0.0
bowlers['RUNS_GIVEN'] = 0.0
bowlers['TOTAL_OVERS'] = 0.0
bowlers['TOTAL_DOTS'] = 0.0
bowlers['BEST_FIGURE'] = 0.0
bowlers['STRIKE_RATE'] = 0.0
bowlers['MAIDENS'] = 0.0
bowlers['PP/DEATH_FIG'] = 0.0
bowlers['CATCHES_TAKEN'] = 0.0
bowlers['CATCHES_DROPPED'] = 0.0
bowlers['RUN_OUT_(%)'] = 0.0
bowlers['RUNS_SAVED'] = 0.0
bowlers['BOUNDARIES_SAVED'] = 0.0

In [23]:
bowlers.columns

Index(['PLAYER_NAME', 'PLAYER_TYPE', 'PLAYER_IPL_TEAM', 'TOTAL_WICKETS',
       'BOWLING_AVG', 'ECONOMY_RATE', '2WK_HAULS', '3WK_HAULS', '4WK_HAULS',
       'RUNS_GIVEN', 'TOTAL_OVERS', 'TOTAL_DOTS', 'BEST_FIGURE', 'STRIKE_RATE',
       'MAIDENS', 'PP/DEATH_FIG', 'CATCHES_TAKEN', 'CATCHES_DROPPED',
       'RUN_OUT_(%)', 'RUNS_SAVED', 'BOUNDARIES_SAVED'],
      dtype='object')

In [24]:
bowlers.head(5)

,PLAYER_NAME,PLAYER_TYPE,PLAYER_IPL_TEAM,TOTAL_WICKETS,BOWLING_AVG,ECONOMY_RATE,2WK_HAULS,3WK_HAULS,4WK_HAULS,RUNS_GIVEN,...,TOTAL_DOTS,BEST_FIGURE,STRIKE_RATE,MAIDENS,PP/DEATH_FIG,CATCHES_TAKEN,CATCHES_DROPPED,RUN_OUT_(%),RUNS_SAVED,BOUNDARIES_SAVED
PLAYER_ID,,,,,,,,,,,,,,,,,,,,,
36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_IPL,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_T20I,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_ODI,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_STATE_T20,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_SMAT_ELITE,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Saving the Dataset

In [25]:
batsman.to_csv('./dataset/IPL_BATSMAN.csv')
bowlers.to_csv('./dataset/IPL_BOWLERS.csv')